from __future__ import annotations


# Clear or commonly accepted Homeric/epic centers. Unclear factions are listed
# below so campaign staff can assign capitals deliberately.
CAPITALS = {
    "Abantes": "Chalcis",
    "Aetolians": "Calydon",
    "Argos": "Argos",
    "Athina": "Athens",
    "Boetians": "Thebes",
    "Carians": "Miletus",
    "Cicones": "Ismarus",
    "Corinthians": "Corinth",
    "Dardania": "Dardania",
    "Dorians": "Doris",
    "Elis": "Elis",
    "Ionia": "Miletus",
    "Ithaca": "Ithaca",
    "Knossos": "Knossos",
    "Lycia": "Xanthus",
    "Maeonians": "Hyde",
    "Miletus": "Miletus",
    "Mysia": "Mysia",
    "Mycenae": "Mycenae",
    "Paphlagonians": "Cytorus",
    "Phaiacians": "Scheria",
    "Phrygians": "Ascania",
    "Phthia": "Phthia",
    "Pylos": "Pylos",
    "Rhodes": "Lindos",
    "Salamis": "Salamis",
    "Sparta": "Sparta",
    "Thracians": "Thrace",
    "Troy": "Troy",
}

UNKNOWN_CAPITAL_NATIONS = (
    "Aegaan Pelasgians",
    "Aenos",
    "Aethaleia",
    "Aethria",
    "Agriophones",
    "Alazones",
    "Anemoessa",
    "Antheada",
    "Apaesos",
    "Apteron",
    "Apsynthioi",
    "Arcadians",
    "Ascanian Phrygians",
    "Asia",
    "Bithyni",
    "Bisaltae",
    "Bottiaeans",
    "Cassopaei",
    "Chersonesos",
    "Curetes",
    "Dindyma",
    "Dionysias",
    "Dolopia",
    "Edonia",
    "Ellopians",
    "Ephesos",
    "Epidayrus",
    "Epirotes",
    "Esperia",
    "Graea",
    "Ilion Hyrtacidae",
    "Ilion Imbrasos",
    "Kyme",
    "Lapiths",
    "Lelegia Minoa",
    "Lycomedes' Dolopians",
    "Macednon",
    "Magnetes",
    "Makaria",
    "Manyan Phrygians",
    "Maeonians of Tmolos",
    "Meliboea",
    "Methymna",
    "Minyes",
    "Mygdonians",
    "Narykos",
    "Noagria",
    "Ozolian Locris",
    "Paeonians",
    "Pelasgiotes",
    "Peraia",
    "Perrhaebi",
    "Phlegra",
    "Phyllis",
    "Tantalis",
    "Teleboans",
    "Tereia",
    "Thessalians",
    "Thrakes",
    "Thyni",
    "Tiryns",
    "Tlawa",
    "Triopion",
    "Troizen",
)


def capital_for_nation(nation: str) -> str:
    return CAPITALS.get(nation, "Unassigned")
